language: rust

env:
  global:
      # Define to true to upload if cargo search will not find crate
    - CARGO_UPLOAD_FIRST_TIME=true
      # Define default branch for docs
    - PAGES_BRANCH_NAME=gh-pages
      # Sets to true in case  of crate's version bump
    - UPDATE_PAGES=false

install:
  - rustc -V
  - cargo -V

script:
    cargo build && cargo test

after_success:
  - |
      if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
        echo "Skip deploy on pull request"
        exit 0
      fi

      # Success
      curl -sSL https://raw.githubusercontent.com/DoumanAsh/douman-ci/master/rust/upload_pages.sh > ~/upload_pages.sh
      curl -sSL https://raw.githubusercontent.com/DoumanAsh/douman-ci/master/rust/upload_rust_crate.sh > ~/upload_rust_crate.sh
      source ~/upload_rust_crate.sh
      bash ~/upload_pages.sh
